# Generated by Django 4.2 on 2024-04-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0003_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
