# Generated by Django 4.2 on 2024-04-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0005_reservation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
