# Generated by Django 4.2 on 2024-04-24 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0006_remove_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
