# Generated by Django 4.2 on 2024-04-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0007_reservation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passager',
        ),
    ]
