# Generated by Django 4.2 on 2024-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0008_delete_passager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
