# Generated by Django 4.2 on 2024-04-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0010_alter_reservation_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
    ]
