# Generated by Django 4.2 on 2024-04-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0011_remove_reservation_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passenger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trajets.passenger'),
        ),
    ]
