# Generated by Django 4.2 on 2024-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0013_rename_passenger_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
        migrations.DeleteModel(
            name='Passengers',
        ),
    ]
