# Generated by Django 4.2 on 2024-04-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0015_passengers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passengers',
        ),
    ]
