# Generated by Django 4.2 on 2024-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0016_delete_passengers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
    ]
