# Generated by Django 4.2 on 2024-04-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0017_passengers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='passengers',
            name='prenom',
        ),
    ]
