# Generated by Django 4.2 on 2024-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajets', '0018_remove_passengers_nom_remove_passengers_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengers',
            name='nom',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='passengers',
            name='prenom',
            field=models.CharField(default='PB DE PASSAGER', max_length=30),
        ),
    ]
