# Generated by Django 4.2 on 2024-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trajects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numero_place',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
